// HARINI's small JavaScript file: products, filters, and a saved shopping cart.
const products = [
  {id:1,name:'Rose Embroidered Kurti',price:1499,category:'Kurtis',image:'https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=700&q=85',description:'A graceful rose-toned kurti with delicate embroidery, made for effortless celebrations.'},
  {id:2,name:'Floral Summer Dress',price:1899,category:'Dresses',image:'https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=700&q=85',description:'A light, breezy floral dress that brings a little sunshine to your day.'},
  {id:3,name:'Elegant Cotton Saree',price:2499,category:'Sarees',image:'https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=700&q=85',description:'Soft cotton drape with a timeless finish, perfect for elegant everyday dressing.'},
  {id:4,name:'Classic Co-ord Set',price:1799,category:'Co-ord Sets',image:'https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?auto=format&fit=crop&w=700&q=85',description:'A polished matching set that makes getting ready beautifully simple.'},
  {id:5,name:'Pink Anarkali Dress',price:2199,category:'Dresses',image:'https://images.unsplash.com/photo-1610030469668-8e9f4e950d4d?auto=format&fit=crop&w=700&q=85',description:'A flowing pink Anarkali designed to make every occasion feel special.'},
  {id:6,name:'Everyday Linen Top',price:999,category:'Tops',image:'https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=700&q=85',description:'A breathable linen top with an easy silhouette for your everyday wardrobe.'},
  {id:7,name:'Festive Silk Kurti',price:1699,category:'Kurtis',image:'https://images.unsplash.com/photo-1610030469668-8e9f4e950d4d?auto=format&fit=crop&w=700&q=85',description:'Rich silk texture and festive details in a kurti made to be remembered.'},
  {id:8,name:'Floral Printed Saree',price:2299,category:'Sarees',image:'https://images.unsplash.com/photo-1583391733981-849840c9ef2f?auto=format&fit=crop&w=700&q=85',description:'An artful floral print on a graceful saree for joyful, colourful moments.'}
];
const categories = [
  ['Sarees','https://images.unsplash.com/photo-1610030469983-98e550d6193c?auto=format&fit=crop&w=500&q=80'],['Kurtis','https://images.unsplash.com/photo-1583391733956-6c78276477e2?auto=format&fit=crop&w=500&q=80'],['Dresses','https://images.unsplash.com/photo-1496747611176-843222e1e57c?auto=format&fit=crop&w=500&q=80'],['Tops','https://images.unsplash.com/photo-1566206091558-7f218b696731?auto=format&fit=crop&w=500&q=80'],['Co-ord Sets','https://images.unsplash.com/photo-1617019114583-affb34d1b3cd?auto=format&fit=crop&w=500&q=80'],['Ethnic Wear','https://images.unsplash.com/photo-1583391733981-849840c9ef2f?auto=format&fit=crop&w=500&q=80']
];
const rupees = n => '₹' + n.toLocaleString('en-IN');
let cart = JSON.parse(localStorage.getItem('hariniCart') || '[]');
function saveCart(){localStorage.setItem('hariniCart',JSON.stringify(cart)); updateCartCount();}
function updateCartCount(){document.querySelectorAll('.cart-count').forEach(el=>el.textContent=cart.reduce((sum,item)=>sum+item.quantity,0));}
function productCard(product){return `<article class="product-card"><button class="heart" aria-label="Add to wishlist">♡</button><a class="product-image" href="product.html?id=${product.id}"><img src="${product.image}" alt="${product.name}"></a><div class="product-info"><h3><a href="product.html?id=${product.id}">${product.name}</a></h3><span class="price">${rupees(product.price)}</span><span class="stars">★★★★★</span></div><button class="add-cart" data-add="${product.id}">Add to Cart</button></article>`;}
function renderProducts(selector,list){document.querySelectorAll(selector).forEach(grid=>grid.innerHTML=list.map(productCard).join(''));}
function addToCart(id,quantity=1){const item=cart.find(p=>p.id===id);if(item)item.quantity+=quantity;else cart.push({id,quantity});saveCart();}
function renderCart(){const holder=document.querySelector('#cart-items');if(!holder)return; if(!cart.length){holder.innerHTML='<div class="empty-cart"><h2>Your bag is waiting.</h2><p>Find something lovely to add to it.</p><a class="button" href="shop.html">Start Shopping</a></div>';}else{holder.innerHTML=cart.map(item=>{const p=products.find(product=>product.id===item.id);return `<article class="cart-item"><img src="${p.image}" alt="${p.name}"><div><h3>${p.name}</h3><p>${rupees(p.price)}</p><button class="remove-item" data-remove="${p.id}">Remove</button></div><div><div class="quantity-control"><button data-change="${p.id}" data-amount="-1">−</button><span>${item.quantity}</span><button data-change="${p.id}" data-amount="1">+</button></div><p>${rupees(p.price*item.quantity)}</p></div></article>`;}).join('');}const total=cart.reduce((sum,item)=>{let p=products.find(product=>product.id===item.id);return sum+p.price*item.quantity},0);document.querySelector('#subtotal').textContent=rupees(total);document.querySelector('#cart-total').textContent=rupees(total);document.querySelector('#total-items').textContent=cart.reduce((sum,item)=>sum+item.quantity,0);}
function renderDetail(){const box=document.querySelector('#product-detail');if(!box)return;const id=Number(new URLSearchParams(location.search).get('id'))||1;const p=products.find(item=>item.id===id)||products[0];box.innerHTML=`<div class="detail-wrap"><img src="${p.image}" alt="${p.name}"><div class="detail-info"><p class="eyebrow">HARINI ${p.category.toUpperCase()}</p><h1>${p.name}</h1><div class="stars">★★★★★ <span> (24 reviews)</span></div><p class="detail-price">${rupees(p.price)}</p><p>${p.description}</p><span class="option-label">SELECT SIZE</span><div class="size-options"><button>XS</button><button>S</button><button class="selected">M</button><button>L</button><button>XL</button></div><span class="option-label">SELECT COLOUR</span><div class="color-options"><button style="background:#d88d91"></button><button style="background:#f0d9c2"></button><button style="background:#3a2520"></button></div><span class="option-label">QUANTITY</span><div class="quantity-control detail-quantity"><button data-detail-amount="-1">−</button><span>1</span><button data-detail-amount="1">+</button></div><div class="detail-actions"><button class="button" data-add="${p.id}">Add to Cart</button><button class="button outline" data-buy="${p.id}">Buy Now</button></div></div></div>`;}
function setupShopFilters(){const grid=document.querySelector('.all-products');if(!grid)return;const search=document.querySelector('#product-search'), category=document.querySelector('#category-filter'),price=document.querySelector('#price-filter'),sort=document.querySelector('#sort-products');function filter(){let result=[...products],term=search.value.toLowerCase();if(term)result=result.filter(p=>p.name.toLowerCase().includes(term));if(category.value!=='all')result=result.filter(p=>p.category===category.value);if(price.value==='under1500')result=result.filter(p=>p.price<1500);if(price.value==='1500to2000')result=result.filter(p=>p.price>=1500&&p.price<=2000);if(price.value==='over2000')result=result.filter(p=>p.price>2000);if(sort.value==='low')result.sort((a,b)=>a.price-b.price);if(sort.value==='high')result.sort((a,b)=>b.price-a.price);grid.innerHTML=result.map(productCard).join('');document.querySelector('#product-total').textContent=result.length;}[search,category,price,sort].forEach(el=>el.addEventListener('input',filter));}
document.addEventListener('click',event=>{let add=event.target.closest('[data-add]');if(add){addToCart(Number(add.dataset.add),Number(document.querySelector('.detail-quantity span')?.textContent)||1);if(event.target.matches('[data-buy]'))location.href='cart.html';}let detailAmount=event.target.closest('[data-detail-amount]');if(detailAmount){const count=detailAmount.parentElement.querySelector('span');count.textContent=Math.max(1,Number(count.textContent)+Number(detailAmount.dataset.detailAmount));}let remove=event.target.closest('[data-remove]');if(remove){cart=cart.filter(item=>item.id!==Number(remove.dataset.remove));saveCart();renderCart();}let change=event.target.closest('[data-change]');if(change){const item=cart.find(i=>i.id===Number(change.dataset.change));item.quantity+=Number(change.dataset.amount);if(item.quantity<1)cart=cart.filter(i=>i!==item);saveCart();renderCart();}if(event.target.closest('.size-options button')){event.target.parentElement.querySelectorAll('button').forEach(b=>b.classList.remove('selected'));event.target.classList.add('selected');}if(event.target.closest('.menu-toggle'))document.querySelector('.main-nav').classList.toggle('open');if(event.target.closest('.search-toggle'))document.querySelector('.search-bar')?.classList.toggle('show');});
document.addEventListener('submit',event=>{if(event.target.matches('.newsletter-form,.contact-form')){event.preventDefault();alert('Thank you for joining HARINI!');event.target.reset();}});
const categoryGrid=document.querySelector('#category-grid');if(categoryGrid)categoryGrid.innerHTML=categories.map(c=>`<a class="category-card" href="shop.html"><img src="${c[1]}" alt="${c[0]}"><span>${c[0]}</span></a>`).join('');
renderProducts('.featured-products',products.slice(0,4));renderProducts('.all-products',products);renderDetail();setupShopFilters();renderCart();updateCartCount();
